### ISSUE TITLE
"Unsecured" website

### ISSUE THREAD

**Issue by kakanikatija** [fathomnet/community-feedback#12]
Perhaps something we need to fix
<img width="933" alt="Screen Shot 2021-10-14 at 5 53 37 AM" src="https://user-images.githubusercontent.com/26979643/137321391-c5b4af04-519c-4bd0-82ea-32f23518083e.png">

**Comment by hohonuuli** [comment]
It is. I even have the signing certificate for it. When i applied TLS to both the website and the microservice, things stopped working. Browser security is not my forte :-(

**Comment by hohonuuli** [comment]
Notes for adding CORS headers for NGINX proxies:

- [How to enable CORS in Nginx proxy server?](https://stackoverflow.com/questions/45986631/how-to-enable-cors-in-nginx-proxy-server)
- [Proxy Server - Blocked by CORS policy](https://stackoverflow.com/questions/63342306/proxy-server-blocked-by-cors-policy-no-access-control-allow-origin-header-i)

**Comment by hohonuuli** [comment]
Dhugal Lindsay reported the following issues when connecting to FathomNet services. I suspect that something is trying to force all traffic to use https. https is enabled but not on the services.

First page was

Secure Connection Failed

An error occurred during a connection to [fathomnet.org:8080](http://fathomnet.org:8080/). SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

   The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
   Please contact the website owners to inform them of this problem.

Learn more…


Second loaded ok

[
 "",
 "1-gallon paint bucket",
 "2G Robotics structured light laser",
 "55-gallon drum",
 "a\u0027a",
 "abandoned research equipment",
 "Abraliopsis",
 "Abraliopsis (Boreabraliopsis) felis",
 "Abraliopsis felis",
 "abyssal",
 "abyssal grenadier",


Third also didn't load

Secure Connection Failed

An error occurred during a connection to [fathomnet.org:8888](http://fathomnet.org:8888/). SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

   The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
   Please contact the website owners to inform them of this problem.

Learn more…

**Comment by hohonuuli** [comment]
We will have both unsecured and secured endpoints. FathomNet will use only the SSL secured ones for the web site. Example changes:

- FathomNet API will be at https://fathomnet/api: <http://fathomnet.org:8080/boundingboxes/count> becomes <https://fathomnet.org/api/boundingboxes/count>
- VARS Knowledgebase will be at https://fathomnet/dsg: <http://dsg.mbari.org/kb/v1/concept> becomes <https://fathomnet.org/dsg/concept>
- Fast WoRMS will be at https://fathomnet/worms: <http://fathomnet.org:8888/names> becomes <https://fathomnet.org/worms/names>

**Comment by hohonuuli** [comment]
Running into https://github.com/micronaut-projects/micronaut-data/issues/1712 on deployment after upgrading micronaut.

**Comment by hohonuuli** [comment]
SSL/CORS setup has been deployed. All traffic to <http://fathomnet.org> is redirected to <https://fathomnet.org>. 

> **Note**
> The swagger-ui is broken. The UI has been moved to <http://fathomnet.org:8080/api/swagger-ui> and the explore bar shows "/swagger/fathomnet-0.0.yml". To view the docs, you will need manually change that to "/api/swagger/fathomnet-0.0.yml".  I'm looking for a fix.

**Comment by hohonuuli** [comment]
I moved the swagger ui back to <http://fathomnet.org:8080/swagger-ui> and it works normally. 

The secured version at <https://fathomnet.org/api/swagger-ui> still uses the wrong path to the openapi yml file. Manually changing that to "/api/swagger/fathomnet-0.0.yml" addresses that.

**Comment by hohonuuli** [comment]
Dhugal checked that FathomNet is working form inside JAMSTEC's fancy firewall. All is good.

**Comment by hohonuuli** [comment]
It's been a few weeks and everything is working. I'm closing this issue.
