### ISSUE TITLE
Longitude wraparound issue

### ISSUE THREAD

**Issue by acmyu** [fathomnet/community-feedback#135]
Hi,

When I ran the python API to find images limited by the bounding box for the Pacific Ocean (minLongitude=128, maxLongitude=-67), it returned empty.
If I remove the minLongitude, maxLongitude constraints, it is able to correctly return a list of images mostly from Monterey Bay (longitude=-122).
![image](https://github.com/fathomnet/community-feedback/assets/12604506/3d8e4087-f2d6-49d5-ad4f-e7d98d3a05f9)
This might be a bug caused by longitude wraparound that happens in the middle of the Pacific Ocean, where it's 180 on one side of the line and -180 on the other side.
![Untitled](https://github.com/fathomnet/community-feedback/assets/12604506/cf6bc416-43d1-44bf-9e28-b1d89442ff3e)
I think to solve the issue, we might need to do:
`maxLon = r.maxLongitude`
`dataLon = d['longitude']`
`if maxLon < r.minLongitude:`
`  maxLon = maxLon % 180 + 180`
`  if dataLon < 0:`
`    dataLon = dataLon % 180 + 180`
where r is the region and d is the image metadata.
I'm not 100% sure if this calculation is correct.
Please let me know if I'm missing something.

**Comment by kevinsbarnard** [comment]
Hi,

The API will take your input parameters literally; when you specify `minLongitude=128, maxLongitude=-67`, it will look for images that have a longitude value > 128 and < -67, so nothing will come back. The API will not pre-process your parameters to handle the wrap-around.

I would recommend breaking this into two separate queries that only specify the min or max:
1. **`minLongitude=128`**`[, maxLongitude=180]`
2. `[minLongitude=-180, ]`**`maxLongitude=-67`**

You can omit the -180/180 bounds since all longitudes should be < 180 and > -180 anyway. And in case you're querying at the North/South poles, you'd need to do this with latitude too 😉

Hope this helps!

**Comment by acmyu** [comment]
Ah, I see. That's a good solution.
Thanks for the help :)
