### ISSUE TITLE
[Suggestion] Concept tree and all descendants as default view / search for taxonomic rank on tree with no entry

### ISSUE THREAD

**Issue by ghost** [fathomnet/community-feedback#5]
At the moment, if you search for "Bathocyroidae" or higher-ranking concepts, you get a "no data available" message if there's no specific entry for it. Or, if you come across it on the home page as seen below, the map view and results give the impression that there's no data available for the family at all unless you manually go into the concept tree (see below).

I don't know if it's possible, but it might be helpful for now to have the concept tree view and default search as "All descendants" for concepts that have entries below them but not for the concept itself. That way you can immediately know whether there's data for a genus or species within that order or family. I hope that makes sense.

![Screen Shot 2021-10-01 at 4 29 22 PM](https://user-images.githubusercontent.com/91396350/135696243-c3857a7c-1cec-42a7-b30e-23f9ba8aa643.png)

https://user-images.githubusercontent.com/91396350/135696447-c520dfbe-54a2-4ba1-826e-bf30f24774a8.mp4

**Comment by kakanikatija** [comment]
I think that's a great suggestion @tropicofdan. If you don't populate the taxonomy provider, it will automatically show results for all descendants. Curious what @hohonuuli thinks about this.

**Comment by ghost** [comment]
Thanks @kakanikatija. I was thinking about how I use the DSG and it's not very often that I'm searching for something extremely specific—usually I'm searching pretty broadly so that I can narrow it down based on what I'm seeing. But I know that some might be using FathomNet _completely_ differently.

A small related idea: for the concept tree search, maybe it'd be better to have the two options as a filter. If anything, it would save a click—right now if you want to keep searching for all descendants, it takes two clicks for each individual search even if left on "all descendants" (big search button -> all descendants).

Rough concept but basically one button with filters:

![searchsuggestion](https://user-images.githubusercontent.com/91396350/137081014-bc159f4f-c86f-49e3-a027-f8a12b3efcd8.png)

For the general search: Perhaps it's something that can be a global setting? I'm probably getting too far ahead of myself, but it would be cool if users could tailor the FathomNet UI a little to their preference. For instance, some might want the concept tree as the default or others might like the map view. Just some thoughts.

**Comment by ermbutler** [comment]
@tropicofdan I agree it should be a preference, or like you presented here just a filter not always presented on button click. It could be presented with checkboxes and be preserved in the user's browser cache. (Created an issue https://github.com/fathomnet/community-feedback/issues/21 for this)

Re: for general search -- I just put comments here https://github.com/fathomnet/community-feedback/issues/22

Re: the original issue Concept tree -- two issues here

1. Screenshot (no data available)
This relates to the way that the autocomplete is hooked up against the backend model, and would require some mapping to go up a concept. I need to see how this is working in more detail if there is a hook on the frontend or backend for this.
2. The video where you actually search -- at this point I feel like I would have a hook to look around up or down the tree, and would at the very least say "0 results for this. Results exist for child concept: Xyz" -- ? Instead of just showing them // either way making it clear what the results are showing.

Tagging this as front/backend to review later.

**Comment by kevinsbarnard** [comment]
We're not planning on implementing this currently, as there's already an option to select all descendants.
