### ISSUE TITLE
[Note] The Downloads and Submissions sections of our user profile

### ISSUE THREAD

**Issue by ghost** [fathomnet/community-feedback#8]
I just wanted to give a heads up in the event that we're not supposed to see this in there.

• Within our user profile, under Downloads, there's 3 of the same collection. If you download any of them, it's just an .html file that says "Loading FathomNet". 

• Under Submissions, there's a long list of collections from @hohonuuli. I'm able to see a menu where I can potentially verify or reject—I didn't press anything, just in case.

![Screen Shot 2021-10-03 at 3 06 41 PM](https://user-images.githubusercontent.com/91396350/135913728-1adf3497-3b5d-4eb6-88bf-083c5b46e3da.png)
![Screen Shot 2021-10-03 at 3 06 59 PM](https://user-images.githubusercontent.com/91396350/135913742-24f5559a-9c89-4943-a142-ab68c6450972.png)

**Comment by hohonuuli** [comment]
@tropicofdan Thanks for the heads up. 

Notes for myself:
- Mark as verified and Reject aren't wired up yet, so they don't actually do anything at the collection level.
- Server side security is already in place and won't allow users without the appropriate roles to make those actions. So the web UI I will fail for most users.
- Read/Write roles should not be shown this page. Need to make that change in the UI

**Comment by hohonuuli** [comment]
Re: Downloads, that's just a placeholder for now (i.e. we're beta :-)

**Comment by ermbutler** [comment]
@hohonuuli  when we meet can discuss --- wrote some notes below, but based on that....

I would suggest we review, and decide what to suppress in beta (ie. Hide features 1,2,3) against this issue, and then make new separate issues to complete the unfinished tasks mentioned here so we can monitor against those tasks before a final release -- giving them a label of some sort?

Here are my notes....
* Mark as verified / Reject -- Can those be hooked up if I have the time? Or is there a backend blocker (bc otherwise I can hide them temporarily on frontend)
* I'm not seeing the read/write role on the page (maybe I am missing it but I can remove it from UI)
* Downloads link --- again I can hide this? or hook it up?
* Is multiple of same collections an issue?
* Submissions being shown should be hidden?

**Comment by hohonuuli** [comment]
> Mark as verified / Reject -- Can those be hooked up if I have the time? Or is there a backend blocker (bc otherwise I can hide them temporarily on frontend)

@ermbutler There isn't necessarily a blocker. There just isn't a single API call in place to execute this. So while it is *possible* with the current API, it's pretty cumbersome. I would temporarily hide this on the front end.

> I'm not seeing the read/write role on the page (maybe I am missing it but I can remove it from UI)

@ermbutler There's a Vuex store (`store/modules/firebase.js`), that will have the current user (including roles) for you to access.

> Downloads link --- again I can hide this? or hook it up?

Hide. I don't think there's any plans right now to implement any part of this.

> Is multiple of same collections an issue?

Nope. 

> Submissions being shown should be hidden?

Keep the submissions!!! That is working.

**Comment by ermbutler** [comment]
Committed a change to develop re: above note, and address the two main concerns in issue
• Downloads - hidden from navigation on left so users cannot get there
• Submissions - Verify and Reject removed from options (now just lists "View")
