### ISSUE TITLE
Add frontend UI for new default concept tree

### ISSUE THREAD

**Issue by kevinsbarnard** [fathomnet/community-feedback#95]
UI to deal with 1 million+ names instead of 5k names (currently all done in memory)

**Comment by ermbutler** [comment]
Notes--

Docs: http://fathomnet.org:8888/docs/

Getting primary name from common:
http://fathomnet.org:8888/taxa/info/starfish

**Comment by ermbutler** [comment]
https://github.com/fathomnet/fathomnet-web-ui/pull/5

**Comment by hohonuuli** [comment]
I've added a new endpoint to get searchable concepts rather than use all concepts in WoRMS. I haven't deployed it yet but it will be at <https://fathomnet.org/api/boundingboxes/list/searchable> and will be a drop in replacement for <https://fathomnet.org/api/boundingboxes/list/concepts>. It adds any terms from worms that will actually return hits in fathomnet when used in an `all descendants` search. I'll deploy it next week.
